In [15]:
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
sent=['the glass odf milk',
'the glass of juice',
'the cup of teas',
'I am a good boy',
'I am a good developer',
'understand the meaning of word',
'your videos are good']

In [17]:
sent

['the glass odf milk',
 'the glass of juice',
 'the cup of teas',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [18]:
voc_size=10000

In [19]:
sent

['the glass odf milk',
 'the glass of juice',
 'the cup of teas',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [20]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9915, 9668, 9566, 3461],
 [9915, 9668, 1670, 863],
 [9915, 335, 1670, 3343],
 [9915, 9401, 216, 2495, 1409],
 [9915, 9401, 216, 2495, 9871],
 [3923, 9915, 7310, 1670, 6383],
 [9785, 421, 6097, 2495]]

In [21]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [22]:
import numpy as sequences

In [24]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[9915 9668 9566 3461    0    0    0    0]
 [9915 9668 1670  863    0    0    0    0]
 [9915  335 1670 3343    0    0    0    0]
 [9915 9401  216 2495 1409    0    0    0]
 [9915 9401  216 2495 9871    0    0    0]
 [3923 9915 7310 1670 6383    0    0    0]
 [9785  421 6097 2495    0    0    0    0]]


In [25]:
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','loss')

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 87ms/step


array([[-0.00721854,  0.03453622, -0.03944723,  0.03598913,  0.010269  ,
         0.01098399, -0.00679116,  0.04286463, -0.03984978,  0.01470591],
       [ 0.03031817,  0.02743113,  0.03272209, -0.01635195, -0.00869466,
        -0.03421996,  0.04517439, -0.0203254 , -0.0084094 ,  0.0249789 ],
       [ 0.04575543, -0.04143709,  0.0305316 , -0.034871  , -0.01120729,
        -0.04984777, -0.03880541,  0.04926577, -0.01084413,  0.03212273],
       [-0.00030761,  0.00329775, -0.01246566,  0.01025928,  0.0207365 ,
         0.01387293,  0.03902728,  0.03762441,  0.0045008 ,  0.04775789],
       [ 0.04879305,  0.01485132,  0.04358425,  0.00741803, -0.0291417 ,
        -0.01205782,  0.02775444, -0.0373652 ,  0.04577089, -0.01555783],
       [ 0.04879305,  0.01485132,  0.04358425,  0.00741803, -0.0291417 ,
        -0.01205782,  0.02775444, -0.0373652 ,  0.04577089, -0.01555783],
       [ 0.04879305,  0.01485132,  0.04358425,  0.00741803, -0.0291417 ,
        -0.01205782,  0.02775444, -0.0373652 

In [30]:
embedded_docs[0]

array([9915, 9668, 9566, 3461,    0,    0,    0,    0])

In [32]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 20ms/step


array([[-0.00721854,  0.03453622, -0.03944723,  0.03598913,  0.010269  ,
         0.01098399, -0.00679116,  0.04286463, -0.03984978,  0.01470591],
       [ 0.03031817,  0.02743113,  0.03272209, -0.01635195, -0.00869466,
        -0.03421996,  0.04517439, -0.0203254 , -0.0084094 ,  0.0249789 ],
       [ 0.04575543, -0.04143709,  0.0305316 , -0.034871  , -0.01120729,
        -0.04984777, -0.03880541,  0.04926577, -0.01084413,  0.03212273],
       [-0.00030761,  0.00329775, -0.01246566,  0.01025928,  0.0207365 ,
         0.01387293,  0.03902728,  0.03762441,  0.0045008 ,  0.04775789],
       [ 0.04879305,  0.01485132,  0.04358425,  0.00741803, -0.0291417 ,
        -0.01205782,  0.02775444, -0.0373652 ,  0.04577089, -0.01555783],
       [ 0.04879305,  0.01485132,  0.04358425,  0.00741803, -0.0291417 ,
        -0.01205782,  0.02775444, -0.0373652 ,  0.04577089, -0.01555783],
       [ 0.04879305,  0.01485132,  0.04358425,  0.00741803, -0.0291417 ,
        -0.01205782,  0.02775444, -0.0373652 